#include "syscall.h"
#include <obsidia/gfx.h>
#include <obsidia/settings.h>
#include <obsidia/theme.h>
#include <obsidia/desktop_layout.h>
#include <obsidia/window.h>

static obs_theme_t active_theme;static const obs_theme_t*theme=&active_theme;
static uint32_t theme_id=OBS_THEME_DEFAULT,panel_edge=OBS_PANEL_TOP,panel_size=46,text_scale=2;
static char*number(char*out,uint32_t v){char r[10];uint32_t n=0;if(!v)*out++='0';while(v){r[n++]=(char)('0'+v%10);v/=10;}while(n)*out++=r[--n];*out=0;return out;}
static void button(obs_canvas_t*c,int32_t x,int32_t y,int32_t w,const char*label,int selected){uint32_t color=selected?theme->colors.selection_background:theme->colors.control_normal;obs_fill_rect(c,x,y,w,34,color);obs_stroke_rect(c,x,y,w,34,selected?2:1,selected?theme->colors.accent_primary:theme->colors.window_border_inactive);obs_draw_text_clipped(c,x+10,y+10,(uint32_t)(w-20),label,selected?theme->colors.selection_foreground:theme->colors.text_primary,theme->metrics.text_scale);}
static void draw(obs_window_t*w){obs_canvas_t c;obs_canvas_init(&c,w->pixels,w->width,w->height,w->width);obs_fill_rect(&c,0,0,(int32_t)w->width,(int32_t)w->height,theme->colors.window_background);uint32_t s=theme->metrics.text_scale;obs_draw_text(&c,18,16,"Live Appearance Settings",theme->colors.text_primary,s);obs_draw_text(&c,18,50,"Theme",theme->colors.text_secondary,s);button(&c,18,70,140,"Default",theme_id==OBS_THEME_DEFAULT);button(&c,170,70,140,"Alternate",theme_id==OBS_THEME_ALTERNATE);obs_draw_text(&c,18,116,"Panel edge",theme->colors.text_secondary,s);button(&c,18,136,140,"Top",panel_edge==OBS_PANEL_TOP);button(&c,170,136,140,"Bottom",panel_edge==OBS_PANEL_BOTTOM);char size[24]="Panel size: ";number(size+12,panel_size);obs_draw_text(&c,18,184,size,theme->colors.text_secondary,s);button(&c,18,204,64,"-",0);button(&c,94,204,64,"+",0);obs_draw_text(&c,18,252,"Text scale",theme->colors.text_secondary,s);button(&c,18,272,64,"1",text_scale==1);button(&c,94,272,64,"2",text_scale==2);button(&c,170,272,64,"3",text_scale==3);os_window_present(w);}
static void set_u32(obs_settings_t*s,uint32_t id,uint32_t type,uint32_t value){obs_setting_value_t v={0};v.type=type;v.u32=value;obs_settings_set(s,id,&v);}
static void click(obs_settings_t*s,int32_t x,int32_t y){if(y>=70&&y<104){if(x>=18&&x<158)set_u32(s,OBS_SETTING_APPEARANCE_THEME,OBS_SETTING_TYPE_ENUM,OBS_THEME_DEFAULT);else if(x>=170&&x<310)set_u32(s,OBS_SETTING_APPEARANCE_THEME,OBS_SETTING_TYPE_ENUM,OBS_THEME_ALTERNATE);}else if(y>=136&&y<170){if(x>=18&&x<158)set_u32(s,OBS_SETTING_PANEL_PRIMARY_EDGE,OBS_SETTING_TYPE_ENUM,OBS_PANEL_TOP);else if(x>=170&&x<310)set_u32(s,OBS_SETTING_PANEL_PRIMARY_EDGE,OBS_SETTING_TYPE_ENUM,OBS_PANEL_BOTTOM);}else if(y>=204&&y<238){if(x>=18&&x<82&&panel_size>40)set_u32(s,OBS_SETTING_PANEL_PRIMARY_SIZE,OBS_SETTING_TYPE_U32,panel_size-8);else if(x>=94&&x<158&&panel_size<152)set_u32(s,OBS_SETTING_PANEL_PRIMARY_SIZE,OBS_SETTING_TYPE_U32,panel_size+8);}else if(y>=272&&y<306){if(x>=18&&x<82)set_u32(s,OBS_SETTING_APPEARANCE_TEXT_SCALE,OBS_SETTING_TYPE_U32,1);else if(x>=94&&x<158)set_u32(s,OBS_SETTING_APPEARANCE_TEXT_SCALE,OBS_SETTING_TYPE_U32,2);else if(x>=170&&x<234)set_u32(s,OBS_SETTING_APPEARANCE_TEXT_SCALE,OBS_SETTING_TYPE_U32,3);}}
static void apply(const obs_settings_event_t*e){if(e->setting_id==OBS_SETTING_APPEARANCE_THEME){theme_id=e->value.enumeration;active_theme=*obs_theme_get((obs_theme_id_t)theme_id);active_theme.metrics.text_scale=text_scale;}else if(e->setting_id==OBS_SETTING_APPEARANCE_TEXT_SCALE){text_scale=e->value.u32;active_theme.metrics.text_scale=text_scale;}else if(e->setting_id==OBS_SETTING_PANEL_PRIMARY_EDGE)panel_edge=e->value.enumeration;else if(e->setting_id==OBS_SETTING_PANEL_PRIMARY_SIZE)panel_size=e->value.u32;}
int obsidia_main(void){int64_t authority=os_handle_find(OS_OBJECT_IPC);if(authority<0)return 1;os_handle_set_inheritable((uint64_t)authority,0);obs_settings_t settings;if(obs_settings_connect_with_authority(&settings,(uint64_t)authority)<0)return 2;obs_setting_value_t v;if(obs_settings_get(&settings,OBS_SETTING_APPEARANCE_THEME,&v)==0)theme_id=v.enumeration;if(obs_settings_get(&settings,OBS_SETTING_APPEARANCE_TEXT_SCALE,&v)==0)text_scale=v.u32;if(obs_settings_get(&settings,OBS_SETTING_PANEL_PRIMARY_EDGE,&v)==0)panel_edge=v.enumeration;if(obs_settings_get(&settings,OBS_SETTING_PANEL_PRIMARY_SIZE,&v)==0)panel_size=v.u32;active_theme=*obs_theme_get((obs_theme_id_t)theme_id);active_theme.metrics.text_scale=text_scale;obs_settings_subscribe(&settings,OBS_SETTINGS_SUBSCRIBE_ALL);obs_window_t window;if(os_window_create(&window,520,340,"Appearance Settings")<0)return 3;draw(&window);static const char ready[]="settings-demo: real settings service client ready\n";sys_fd_write(1,ready,sizeof(ready)-1);
    for(;;){int processed=0,redraw=0;obs_settings_event_t changed;for(uint32_t i=0;i<16&&obs_settings_try_next(&settings,&changed)>0;i++){apply(&changed);processed=redraw=1;}for(uint32_t i=0;i<32;i++){obs_window_event_t e;int n=os_window_try_next_event(&window,&e);if(n<=0)break;processed=1;if(e.type==OBS_WINDOW_EVENT_CLOSE){os_window_close(&window);obs_settings_close(&settings);return 0;}if(e.type==OBS_WINDOW_EVENT_RESIZE)redraw=1;else if(e.type==OBS_WINDOW_EVENT_MOUSE_BUTTON&&e.code==1&&!e.value){click(&settings,e.x,e.y);redraw=1;}}if(redraw)draw(&window);if(processed)sys_yield();else sys_sleep(1);}
}
